import { FormEvent, useMemo, useState } from "react";
import type { Agent } from "../shared/types";
import { AgentMark } from "./AgentMark";
import { ContextPicker } from "./ContextPicker";

type RuntimeAgent = "claude-code" | "codex";
const MODELS = {
  "claude-code": [{ id: "opus", label: "Opus", detail: "Deep collaboration", name: "Opus" }, { id: "fable", label: "Fable", detail: "Fast expressive thinking", name: "Fable" }, { id: "sonnet", label: "Sonnet", detail: "Balanced everyday work", name: "Sonnet" }],
  codex: [{ id: "current", label: "Configured", detail: "Use the Codex default", name: "Codex" }, { id: "gpt-5.6-sol", label: "GPT Sol", detail: "Frontier coding model", name: "GPT Sol" }, { id: "gpt-5.6-terra", label: "GPT Terra", detail: "Balanced coding model", name: "GPT Terra" }],
};

export function AddCollaborator({ roomId, defaultCwd, onClose, onCreated }: { roomId: string; defaultCwd: string; onClose: () => void; onCreated: (agent: Agent) => void }) {
  const [runtime, setRuntime] = useState<RuntimeAgent>("claude-code"); const [model, setModel] = useState("opus"); const [customModel, setCustomModel] = useState(""); const [name, setName] = useState("Opus"); const [cwd, setCwd] = useState(defaultCwd); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [created, setCreated] = useState<Agent | null>(null);
  const choices = MODELS[runtime]; const effectiveModel = model === "custom" ? customModel.trim() : model; const selected = useMemo(() => choices.find((choice) => choice.id === model), [choices, model]);
  function chooseRuntime(next: RuntimeAgent) { const first = MODELS[next][0]; setRuntime(next); setModel(first.id); setName(first.name); setCustomModel(""); }
  async function add(event: FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { const response = await fetch(`/api/rooms/${roomId}/participants`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ runtime, model: effectiveModel, name: name.trim(), cwd: cwd.trim() || null }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); onCreated(data); setCreated(data); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); } finally { setSaving(false); } }
  if (created) return <ContextPicker roomId={roomId} agent={created} onClose={onClose} onSelected={(agent) => { onCreated(agent); onClose(); }} />;
  return <div className="collaborator-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="collaborator-dialog" role="dialog" aria-modal="true"><header className="collaborator-header"><div><span className="section-label">Room participant</span><h2>Add a collaborator</h2><p>Attach another real runtime. No agent-building ceremony.</p></div><button className="picker-close" onClick={onClose}>×</button></header><form onSubmit={add}>
    <div className="collaborator-section"><span className="collaborator-label">Runtime</span><div className="runtime-choices">{(["claude-code", "codex"] as RuntimeAgent[]).map((choice) => <button type="button" key={choice} className={runtime === choice ? "selected" : ""} onClick={() => chooseRuntime(choice)}><span className={`avatar ${choice}`}><AgentMark runtime={choice} fallback={choice} /></span><span><strong>{choice === "claude-code" ? "Claude Code" : "Codex"}</strong><small>Your installed runtime</small></span></button>)}</div></div>
    <div className="collaborator-section"><span className="collaborator-label">Model</span><div className="model-choices">{choices.map((choice) => <button type="button" key={choice.id} className={model === choice.id ? "selected" : ""} onClick={() => { setModel(choice.id); setName(choice.name); }}><strong>{choice.label}</strong><small>{choice.detail}</small></button>)}<button type="button" className={model === "custom" ? "selected" : ""} onClick={() => { setModel("custom"); setName(runtime === "codex" ? "Codex" : "Claude"); }}><strong>Custom</strong><small>Any model ID</small></button></div>{model === "custom" && <input className="collaborator-input model-input" autoFocus value={customModel} onChange={(event) => setCustomModel(event.target.value)} placeholder="Model ID" />}</div>
    <div className="collaborator-fields"><label><span>Name in this room</span><input className="collaborator-input" value={name} onChange={(event) => setName(event.target.value)} placeholder={selected?.name} /></label><label><span>Working folder</span><input className="collaborator-input path-input" value={cwd} onChange={(event) => setCwd(event.target.value)} placeholder="Choose context next" /></label></div>
    {error && <div className="collaborator-error">{error}</div>}<footer className="collaborator-footer"><p>Next, choose a project and optional exact session.</p><button className="picker-confirm" disabled={saving || !name.trim() || !effectiveModel}>{saving ? "Adding…" : "Continue"}</button></footer>
  </form></section></div>;
}
