import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Agent, RuntimeCatalogEntry, RuntimeId } from "../shared/types";
import { AgentMark } from "./AgentMark";
import { ContextPicker } from "./ContextPicker";
import { guidedProjectCwd } from "./guidedDemo";

const guidedClaudeCatalog: RuntimeCatalogEntry[] = [{
  descriptor: { id: "claude-code", displayName: "Claude Code", lab: "Anthropic", minimumVersion: null, setupCommand: "", loginCommand: "", updateCommand: "", capabilities: { exactResume: true, modelDiscovery: true, arbitraryModels: true, projectDiscovery: true, transport: "jsonl", safety: "Plan mode" }, presets: [] },
  probe: { runtime: "claude-code", status: "ready", installed: true, authenticated: true, supported: true, version: "2.1.4", executable: "/usr/local/bin/claude", message: "Ready", action: null },
  models: [{ id: "opus", label: "Opus", detail: "Deep reasoning and synthesis", name: "Opus" }, { id: "sonnet", label: "Sonnet", detail: "Fast, balanced collaboration", name: "Sonnet" }, { id: "fable", label: "Fable", detail: "Configured Claude profile", name: "Fable" }],
}];

function defaultName(runtime: RuntimeCatalogEntry, modelId: string) {
  const model = runtime.models.find((choice) => choice.id === modelId);
  return model?.name && model.name !== "Configured default" ? model.name : runtime.descriptor.displayName.replace(" Build", "").replace(" Code", "");
}

export function AddCollaborator({ roomId, defaultCwd, onClose, onCreated, guided = false }: { roomId: string; defaultCwd: string; onClose: () => void; onCreated: (agent: Agent) => void; guided?: boolean }) {
  const [catalog, setCatalog] = useState<RuntimeCatalogEntry[]>([]); const [runtime, setRuntime] = useState<RuntimeId | null>(null); const [model, setModel] = useState(""); const [customModel, setCustomModel] = useState(""); const [name, setName] = useState(""); const [cwd, setCwd] = useState(defaultCwd); const [probing, setProbing] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [created, setCreated] = useState<Agent | null>(null);
  const selectedRuntime = useMemo(() => catalog.find((entry) => entry.descriptor.id === runtime) ?? null, [catalog, runtime]);
  const choices = selectedRuntime?.models ?? []; const effectiveModel = model === "custom" ? customModel.trim() : model; const selected = useMemo(() => choices.find((choice) => choice.id === model), [choices, model]);

  useEffect(() => { if (guided) { setCatalog(guidedClaudeCatalog); chooseRuntime(guidedClaudeCatalog[0], true); setCwd(guidedProjectCwd); setProbing(false); return; } const controller = new AbortController(); setProbing(true); fetch("/api/runtimes", { signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error((await response.json()).error); return response.json(); }).then((data) => { const entries = data.runtimes as RuntimeCatalogEntry[]; setCatalog(entries); const first = entries.find((entry) => entry.probe.status === "ready"); if (first) chooseRuntime(first, true); }).catch((caught) => caught.name !== "AbortError" && setError(caught instanceof Error ? caught.message : String(caught))).finally(() => setProbing(false)); return () => controller.abort(); }, [guided]);

  function chooseRuntime(next: RuntimeCatalogEntry, initial = false) { if (next.probe.status !== "ready") return; const first = next.models[0] ?? next.descriptor.presets[0]; setRuntime(next.descriptor.id); setModel(first?.id ?? "current"); setName(defaultName(next, first?.id ?? "current")); setCustomModel(""); if (!initial) setError(null); }
  async function refresh() { if (guided) return; setProbing(true); try { const response = await fetch("/api/runtimes?refresh=true"); const data = await response.json(); if (!response.ok) throw new Error(data.error); setCatalog(data.runtimes); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); } finally { setProbing(false); } }
  async function add(event: FormEvent) { event.preventDefault(); if (!runtime) return; setSaving(true); setError(null); try { if (guided) { const now = new Date().toISOString(); const data: Agent = { id: `guided-${name.trim().toLowerCase().replace(/\W+/g, "-")}`, runtime, model: effectiveModel, name: name.trim(), cwd: cwd.trim() || null, sessionId: null, status: "available", createdAt: now, updatedAt: now }; onCreated(data); setCreated(data); return; } const response = await fetch(`/api/rooms/${roomId}/participants`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ runtime, model: effectiveModel, name: name.trim(), cwd: cwd.trim() || null }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); onCreated(data); setCreated(data); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); } finally { setSaving(false); } }
  if (created) return <ContextPicker roomId={roomId} agent={created} onClose={onClose} onSelected={(agent) => { onCreated(agent); onClose(); }} guided={guided} />;
  return <div className="collaborator-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="collaborator-dialog" role="dialog" aria-modal="true" aria-labelledby="add-collaborator-title"><header className="collaborator-header"><div><span className="section-label">Room participant</span><h2 id="add-collaborator-title">Add a collaborator</h2><p>Choose a runtime, then connect a project or an existing session.</p></div><button className="picker-close" onClick={onClose} aria-label="Close">×</button></header><form onSubmit={add}>
    <div className="collaborator-section"><div className="collaborator-label runtime-label-row"><span>Runtime</span><button type="button" onClick={() => void refresh()} disabled={probing}>{probing ? "Checking…" : "Refresh"}</button></div><div className="runtime-choices">{catalog.map((entry) => { const ready = entry.probe.status === "ready"; return <button type="button" key={entry.descriptor.id} className={`${runtime === entry.descriptor.id ? "selected" : ""} ${!ready ? "unavailable" : ""}`} onClick={() => chooseRuntime(entry)} disabled={!ready} aria-label={`${entry.descriptor.displayName}: ${entry.probe.message}`}><span className={`avatar ${entry.descriptor.id}`}><AgentMark runtime={entry.descriptor.id} fallback={entry.descriptor.displayName} /></span><span><strong>{entry.descriptor.displayName}</strong><small>{ready ? `${entry.probe.version ?? "Installed"} · ready` : entry.probe.message}</small>{!ready && entry.probe.action && <code>{entry.probe.action}</code>}</span><i /></button>; })}{probing && !catalog.length && Array.from({ length: 4 }, (_, index) => <span className="runtime-skeleton" key={index} />)}</div></div>
    {selectedRuntime && <><div className="collaborator-section"><span className="collaborator-label">Model</span><div className="model-choices">{choices.map((choice) => <button type="button" key={choice.id} className={model === choice.id ? "selected" : ""} onClick={() => { setModel(choice.id); setName(defaultName(selectedRuntime, choice.id)); }}><strong>{choice.label}</strong><small>{choice.detail}</small></button>)}<button type="button" className={model === "custom" ? "selected" : ""} onClick={() => { setModel("custom"); setName(selectedRuntime.descriptor.displayName); }}><strong>Custom</strong><small>Any model ID</small></button></div>{model === "custom" && <input className="collaborator-input model-input" autoFocus value={customModel} onChange={(event) => setCustomModel(event.target.value)} placeholder="Model ID" />}</div>
    <div className="collaborator-fields"><label><span>Name in this room</span><input className="collaborator-input" value={name} onChange={(event) => setName(event.target.value)} placeholder={selected?.name} /></label><label><span>Working folder</span><input className="collaborator-input path-input" value={cwd} onChange={(event) => setCwd(event.target.value)} placeholder="Choose context next" /></label></div></>}
    {error && <div className="collaborator-error">{error}</div>}<footer className="collaborator-footer"><p>{probing ? "Checking your installed runtimes…" : selectedRuntime ? "Next, choose a project and optional exact session." : "No authenticated runtime is currently ready."}</p><button className="picker-confirm" disabled={saving || !runtime || !name.trim() || !effectiveModel}>{saving ? "Adding…" : "Continue"}</button></footer>
  </form></section></div>;
}
