import { useEffect, useMemo, useState } from "react";
import type { Agent, ProjectContext, SessionContext } from "../shared/types";

function relativeTime(timestamp: string) { const minutes = Math.max(1, Math.floor((Date.now() - Date.parse(timestamp)) / 60_000)); if (minutes < 60) return `${minutes}m ago`; const hours = Math.floor(minutes / 60); if (hours < 24) return `${hours}h ago`; return `${Math.floor(hours / 24)}d ago`; }
function shortPath(path: string) { const parts = path.split("/").filter(Boolean); return parts.length > 3 ? `…/${parts.slice(-3).join("/")}` : path; }
function readableSize(bytes: number) { return bytes < 1_048_576 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1_048_576).toFixed(1)} MB`; }

export function ContextPicker({ roomId, agent, onClose, onSelected }: { roomId: string; agent: Agent; onClose: () => void; onSelected: (agent: Agent) => void }) {
  const runtime = agent.runtime === "codex" ? "codex" : "claude-code";
  const [projects, setProjects] = useState<ProjectContext[]>([]); const [sessions, setSessions] = useState<SessionContext[]>([]); const [query, setQuery] = useState(""); const [projectId, setProjectId] = useState<string | null>(null); const [sessionId, setSessionId] = useState<string | null>(agent.sessionId); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [manual, setManual] = useState(false); const [manualPath, setManualPath] = useState(agent.cwd ?? ""); const [manualSession, setManualSession] = useState(agent.sessionId ?? ""); const [error, setError] = useState<string | null>(null);
  const project = useMemo(() => projects.find((item) => item.id === projectId) ?? null, [projects, projectId]);
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(() => { setLoading(true); fetch(`/api/contexts/${runtime}/projects?q=${encodeURIComponent(query)}`, { signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error((await response.json()).error); return response.json(); }).then((data) => { setProjects(data.projects); setProjectId((current) => current && data.projects.some((item: ProjectContext) => item.id === current) ? current : data.projects.find((item: ProjectContext) => item.cwd === agent.cwd)?.id ?? data.projects[0]?.id ?? null); setError(null); }).catch((caught) => caught.name !== "AbortError" && setError(String(caught))).finally(() => setLoading(false)); }, query ? 220 : 0); return () => { clearTimeout(timer); controller.abort(); }; }, [agent.cwd, query, runtime]);
  useEffect(() => { if (!projectId) return setSessions([]); const controller = new AbortController(); fetch(`/api/contexts/${runtime}/projects/${encodeURIComponent(projectId)}/sessions?limit=40`, { signal: controller.signal }).then((response) => response.json()).then((data) => { setSessions(data.sessions ?? []); if (project?.cwd !== agent.cwd) setSessionId(null); }).catch((caught) => caught.name !== "AbortError" && setError(String(caught))); return () => controller.abort(); }, [agent.cwd, project?.cwd, projectId, runtime]);
  async function save(cwd: string, nextSession: string | null) { setSaving(true); setError(null); try { const response = await fetch(`/api/rooms/${roomId}/participants/${agent.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ cwd, sessionId: nextSession }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); onSelected(data); onClose(); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); } finally { setSaving(false); } }
  return <div className="context-picker-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="context-picker" role="dialog" aria-modal="true"><header className="picker-header"><div><span className="section-label">{runtime === "codex" ? "Codex task context" : "Claude working context"}</span><h2>Where should {agent.name} pick up?</h2><p>Choose a project, then begin clean or resume an exact conversation.</p></div><button className="picker-close" onClick={onClose}>×</button></header>
    <div className="picker-search"><span>⌕</span><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${runtime === "codex" ? "Codex" : "Claude"} projects…`} />{query && <button onClick={() => setQuery("")}>Clear</button>}</div>{error && <div className="picker-error">{error}</div>}
    <div className="picker-columns"><div className="project-column"><div className="picker-column-label"><span>Projects</span><small>{projects.length}</small></div><div className="picker-scroll project-results">{loading && !projects.length ? <PickerLoading rows={7} /> : projects.map((item) => <button key={item.id} className={`project-result ${projectId === item.id ? "selected" : ""}`} onClick={() => setProjectId(item.id)}><span className="project-glyph">{item.name.slice(0, 1).toUpperCase()}</span><span className="project-result-copy"><strong>{item.name}</strong><small>{shortPath(item.parentPath)}</small><span>{relativeTime(item.updatedAt)} · {item.sessionCount} session{item.sessionCount === 1 ? "" : "s"}</span></span>{!item.exists && <span className="missing-project">missing</span>}</button>)}{!loading && !projects.length && <div className="picker-empty"><strong>No matching projects</strong><span>Try another name or use a manual path.</span></div>}</div></div>
      <div className="session-column"><div className="picker-column-label"><span>{project?.name ?? "Sessions"}</span><small>{project ? shortPath(project.cwd) : ""}</small></div><div className="picker-scroll session-results">{project && <><button className={`session-result new-session ${sessionId === null ? "selected" : ""}`} onClick={() => setSessionId(null)}><span className="session-radio"><i /></span><span className="session-result-copy"><strong>Start a new Polychat thread</strong><p>Use project instructions and memory without attaching an older transcript.</p><span className="recommended-label">Recommended for a new topic</span></span></button>{project.cwd === agent.cwd && agent.sessionId && <button className={`session-result current-session ${sessionId === agent.sessionId ? "selected" : ""}`} onClick={() => setSessionId(agent.sessionId)}><span className="session-radio"><i /></span><span className="session-result-copy"><strong>Continue current Polychat thread</strong><p>Keep the exact runtime conversation already attached here.</p></span></button>}</>}{sessions.map((session) => <button key={session.id} className={`session-result ${sessionId === session.id ? "selected" : ""}`} onClick={() => setSessionId(session.id)}><span className="session-radio"><i /></span><span className="session-result-copy"><strong>{session.title}</strong><p>{session.lastPrompt || session.preview || "Saved runtime conversation"}</p><span className="session-meta">{relativeTime(session.updatedAt)}{session.source ? ` · ${session.source}` : ""} · {readableSize(session.size)}</span></span></button>)}</div></div></div>
    <footer className="picker-footer"><button className="manual-toggle" onClick={() => setManual((value) => !value)}>{manual ? "Hide manual setup" : "Use a path manually"}</button>{manual ? <div className="manual-context-fields"><input value={manualPath} onChange={(event) => setManualPath(event.target.value)} placeholder="Project directory" /><input value={manualSession} onChange={(event) => setManualSession(event.target.value)} placeholder="Optional session ID" /><button className="picker-confirm" disabled={!manualPath || saving} onClick={() => void save(manualPath, manualSession || null)}>Use manual context</button></div> : <div className="picker-footer-actions"><span>{project ? `${project.name} · ${sessionId ? "resume exact session" : "new thread"}` : "No project selected"}</span><button className="picker-confirm" disabled={!project || !project.exists || saving} onClick={() => project && void save(project.cwd, sessionId)}>{saving ? "Connecting…" : "Use this context"}</button></div>}</footer>
  </section></div>;
}
function PickerLoading({ rows }: { rows: number }) { return <div className="picker-loading">{Array.from({ length: rows }, (_, index) => <span key={index} />)}</div>; }
