import type { Agent, ChatMessage, ProjectContext, RoomState, SessionContext } from "../shared/types";

export const guidedProjectCwd = "/Users/riley/Documents/polyphonic";
const startedAt = "2026-08-12T19:12:00.000Z";

export const guidedAgents: Agent[] = [
  { id: "guided-riley", name: "Riley", runtime: "human", model: null, cwd: guidedProjectCwd, sessionId: null, status: "available", createdAt: startedAt, updatedAt: startedAt },
  { id: "guided-sol", name: "GPT Sol", runtime: "codex", model: "gpt-5.6-sol", cwd: guidedProjectCwd, sessionId: "polyphonic-sol-spec", status: "available", createdAt: startedAt, updatedAt: startedAt },
  { id: "guided-fable", name: "Fable", runtime: "claude-code", model: "fable", cwd: guidedProjectCwd, sessionId: "polyphonic-fable-review", status: "available", createdAt: startedAt, updatedAt: startedAt },
  { id: "guided-kimi", name: "Kimi", runtime: "kimi-code", model: "kimi-k2.5", cwd: guidedProjectCwd, sessionId: "polyphonic-kimi-review", status: "available", createdAt: startedAt, updatedAt: startedAt },
  { id: "guided-grok", name: "Grok", runtime: "grok", model: "grok-code-fast-1", cwd: guidedProjectCwd, sessionId: "polyphonic-grok-review", status: "available", createdAt: startedAt, updatedAt: startedAt },
];

export const guidedOpeningMessage: ChatMessage = {
  id: "guided-opening", roomId: "guided-polyphonic", senderId: "guided-riley", senderName: "Riley", senderRuntime: "human",
  content: "Hey Sol, can you open Polychat and get Fable, Kimi, and Grok’s thoughts on your recommended spec for improving Polyphonic’s messaging performance?",
  status: "complete", replyTo: null, metadata: { audience: "room", recipientAgentIds: ["guided-sol", "guided-fable", "guided-kimi", "guided-grok"] }, createdAt: startedAt, updatedAt: startedAt,
};

export const guidedInitialState: RoomState = {
  room: { id: "guided-polyphonic", name: "Polyphonic messaging performance", projectCwd: guidedProjectCwd, meetingStatus: "live", hostAgentId: "guided-sol", hostExpiresAt: null, archivedAt: null, createdAt: startedAt, updatedAt: startedAt },
  agents: guidedAgents,
  messages: [guidedOpeningMessage],
  councils: [], eventCursor: 1,
};

export const guidedTurns: Array<{ id: string; senderId: string; content: string; pause: number }> = [
  { id: "guided-sol-spec", senderId: "guided-sol", pause: 900, content: "Here’s the spec I’m recommending after tracing the current path. The delay is not primarily model latency; Polyphonic blocks visible progress while it rebuilds conversation context, resolves participant state, and waits for the first provider event.\n\nI’d split delivery into three independently observable phases: acknowledge the user turn immediately, hydrate context behind a room-cursor boundary, then attach the provider stream. Context snapshots should be cached by committed cursor so a long stable prefix is never ranked twice. The UI gets an immediate accepted state, but it only claims a participant is thinking once dispatch actually begins.\n\nThe part I want pressure-tested is ordering. I’m proposing one room sequencer for durable events, with provider streams remaining independent after their invocation cursor is reserved." },
  { id: "guided-fable-1", senderId: "guided-fable", pause: 1100, content: "I agree with the phase split, but I would not let “accepted” become a cosmetic promise. It needs a durable meaning: Polyphonic has recorded the turn and owns the obligation to either dispatch it or surface a terminal failure. Otherwise we improve perceived speed by making uncertainty less visible.\n\nI’d define a small delivery state machine—accepted, context-ready, dispatched, streaming, settled—and persist only transitions that matter after restart. The room can render optimistically from the accepted event, while recovery remains honest.\n\nMy disagreement is with reserving ordering at invocation time. A slow context build could reserve the room ahead of a fast direct message and recreate the feeling of blockage in a different layer." },
  { id: "guided-kimi-1", senderId: "guided-kimi", pause: 1000, content: "The prefix cache is viable if the key is more specific than room cursor alone. I would use `{roomId, headEventId, participantId, contextPolicyVersion}`. Participant and policy belong in the key because two agents can read the same room through different context windows.\n\nFor invalidation, don’t delete old snapshots. Treat them as immutable and promote a new head pointer after assembly succeeds. That removes a lock from the hot path and makes rollback cheap. The live tail can be appended in memory, but the final invocation envelope should record exactly which prefix and tail event range it used.\n\nI think Fable is right about reservation timing. Sequence durable room events, not unfinished work. Assign the invocation cursor only after context is ready." },
  { id: "guided-grok-1", senderId: "guided-grok", pause: 1200, content: "There are two races hiding here. First: context finishes at cursor 410, another agent commits at 411, and the invocation is promoted with a snapshot that looks current but is already stale. Second: cancellation arrives after provider launch but before Polyphonic records `dispatched`, leaving an orphan stream that can still write into the room.\n\nI’d require compare-and-swap against the room head when promoting context-ready to dispatched. If head moved, rebuild only the tail and retry. For cancellation, allocate an invocation ID before launch and make every subsequent provider event prove that ID is still active.\n\nThe spec is close, but “independent provider streams” needs one qualification: independent transport, shared commit gate. Otherwise fast tokens can outrun the ordering contract." },
  { id: "guided-sol-synthesis", senderId: "guided-sol", pause: 900, content: "That sharpens it. Revised recommendation:\n\n1. Persist the user turn immediately and expose `accepted` as a real recovery guarantee.\n2. Cache immutable context prefixes by room head, participant, and policy version; append and validate only the live tail.\n3. Move invocation reservation until context-ready, then compare-and-swap against the current room head.\n4. Give provider transports independent streaming, but pass every delta through a shared invocation-ID commit gate.\n5. Make restart recovery derive from the persisted delivery state machine rather than guessing from participant status.\n\nThat should cut time-to-visible-state to effectively immediate and remove most repeated context work without weakening ordering. Fable, Kimi, Grok—unless you see a remaining blocker, I’d make this the implementation spec." },
];

export const guidedOpusResponse = "I’m aligned with the revised direction, but the existing Polyphonic context makes one boundary especially important: the room event ledger and the provider transcript are not the same authority. The ledger should decide what work exists and in what order; the native provider session should remain evidence of how one participant produced its answer.\n\nThat means the context-prefix cache cannot be reconstructed from provider transcripts after a crash. It must be derivable from committed Polyphonic events alone, with the runtime session ID attached as provenance rather than used as state. I would also keep `accepted` and `dispatched` user-visible only through behavior—not additional status chrome—unless a turn stalls.\n\nWith that correction, the spec is coherent: durable acceptance, cursor-keyed context materialization, compare-and-swap dispatch, and an invocation commit gate. I would ship it behind instrumentation first and measure accepted-to-dispatched, dispatched-to-first-token, tail-rebuild frequency, and rejected late deltas.";

export const guidedProjects: ProjectContext[] = [
  { id: "guided-polyphonic-project", runtime: "claude-code", name: "polyphonic", cwd: guidedProjectCwd, parentPath: "/Users/riley/Documents", updatedAt: "2026-08-12T18:52:00.000Z", sessionCount: 4, hasMemory: true, exists: true },
  { id: "guided-polychat-project", runtime: "claude-code", name: "polychat", cwd: "/Users/riley/Documents/polychat", parentPath: "/Users/riley/Documents", updatedAt: "2026-08-12T17:34:00.000Z", sessionCount: 3, hasMemory: true, exists: true },
];

export const guidedSessions: SessionContext[] = [
  { id: "opus-polyphonic-messaging", title: "Messaging performance and delivery semantics", preview: "Tracing context hydration, dispatch ordering, and provider stream latency.", lastPrompt: "Review the messaging pipeline and preserve continuity through the performance refactor.", branch: "performance/messaging", createdAt: "2026-08-10T16:20:00.000Z", updatedAt: "2026-08-12T18:52:00.000Z", size: 184320, isSidechain: false, source: "Claude Code" },
  { id: "opus-polyphonic-runtime", title: "Runtime routing and session continuity", preview: "Provider bindings, resumable sessions, and room event ownership.", lastPrompt: "Define the boundary between native runtime sessions and Polyphonic room state.", branch: "runtime/routing", createdAt: "2026-08-09T14:10:00.000Z", updatedAt: "2026-08-11T21:18:00.000Z", size: 143360, isSidechain: false, source: "Claude Code" },
  { id: "opus-polyphonic-streams", title: "Streaming UI and failure recovery", preview: "First-token latency, interrupted turns, and restart-safe delivery states.", lastPrompt: "Pressure-test the streaming UX against broker and provider failures.", branch: null, createdAt: "2026-08-08T11:05:00.000Z", updatedAt: "2026-08-10T19:42:00.000Z", size: 102400, isSidechain: false, source: "Claude Code" },
];
